package org.acme.order;


/**
 * A single line in a customer order.
 *
 * <p>Generated by ggen from RDF ontology. Do not edit — regenerate with {@code ggen sync}.
 */

public record OrderItem(
    // TODO: add record components from ontology
) {

    /** Compact constructor — validates all inputs. */
    public OrderItem {
        // TODO: add validation
    }
}
