package org.acme.order;


/**
 * Discriminated union of payment lifecycle states.
 *
 * <p>Generated by ggen from RDF ontology. Do not edit — regenerate with {@code ggen sync}.
 */

public sealed interface PaymentStatus
    permits PaymentStatus.Success, PaymentStatus.Failure {

    /** Successful variant. */
    record Success(String value) implements PaymentStatus {}

    /** Failure variant. */
    record Failure(String reason) implements PaymentStatus {}

    // ── Factory methods ──────────────────────────────────────────────────────

    static PaymentStatus success(String value) {
        return new Success(value);
    }

    static PaymentStatus failure(String reason) {
        return new Failure(reason);
    }

    // ── Pattern-matching helpers ─────────────────────────────────────────────

    default boolean isSuccess() {
        return this instanceof Success;
    }

    default boolean isFailure() {
        return this instanceof Failure;
    }
}
